### ISSUE TITLE
Ugly formatting of linebreaks

### ISSUE THREAD

**Issue by barksten** [obihann/archey-osx#20] opened 2015-10-15 17:13 UTC
I just updated Archey via homebrew.
```
$ brew info archey
archey: stable 1.5, HEAD
Archey script for OS X
https://obihann.github.io/archey-osx/
/usr/local/Cellar/archey/1.4 (3 files, 12K)
  Built from source
/usr/local/Cellar/archey/1.5 (4 files, 16K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/archey.rb
```
My default terminal is 80 chars wide and after the update it looks bad:
```
Last login: Thu Oct 15 19:01:59 on ttys000

                 ###                  User: <<removed>>
               ####                   Hostname: <<removed>>
               ###                    Distro: OS X 10.11
       #######    #######             Kernel: Darwin
     ######################           Uptime: 19:06  up 9 days, 23:10, 2 users, 
load averages: 0.74 0.82 0.91
    #####################             Shell: /bin/bash
    ####################              Terminal: xterm-256color Apple Terminal
    ####################              Packages: 20
    #####################             CPU: <<removed>>
     ######################           Memory: <<removed>>
      ####################            Disk: <<removed>>
        ################              Battery: <<removed>>
         ####     #####               IP Address: <<removed>>


$ 
```
I don't remember how the previous version looked but I'm 100% sure that the Uptime didn't break the logo.

**Comment by obihann** [comment] 2015-10-15 17:35
Thanks for pointing this out, I'll try to get it fixed in the next few days.

**Comment by obihann** [comment] 2015-10-18 23:05
Marking this a duplicate of #18, the regex broke that displayed uptime, its fixed now and should be released later this week.

**Closed** 2015-10-30 15:18 UTC
Labels: duplicate
